# Generated by Django 3.1 on 2023-01-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230126_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharelinks', to='base.file'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='folder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharelinks', to='base.folder'),
        ),
    ]
